console.log('📊 Gemini API Quota Information:');
console.log('');
console.log('🚫 Issue: You have exceeded your Gemini API free tier quota');
console.log('📈 Free Tier Limit: 50 requests per day per model');
console.log('⏰ Reset Time: Quotas reset daily');
console.log('');
console.log('💡 Solutions:');
console.log('1. Wait for quota reset (resets daily)');
console.log('2. Upgrade to paid plan for higher limits');
console.log('3. Use fallback mode (server will work with limited functionality)');
console.log('');
console.log('🔗 More info: https://ai.google.dev/gemini-api/docs/rate-limits');
console.log('');
console.log('✅ Your RAG chatbot is still functional with:');
console.log('- Vector search working');
console.log('- Fallback response generation');
console.log('- All ingested articles available');
console.log('');
console.log('🎯 The server is running and ready to use!');
